export const products = [
  {
    name: "T-shirt",
    price: 2000,
    sizes: ["S", "M", "L", "XL"],
    description: "A comfortable cotton t-shirt",
    category: "Casual",
    image_url: "/placeholder.png",
  },
  {
    name: "Dress",
    price: 3500,
    sizes: ["S", "M"],
    description: "A classy dress",
    category: "Formal",
    image_url: "/placeholder.png",
  },
  {
    name: "Jacket",
    price: 2850,
    sizes: ["M", "L", "XL"],
    description: "A nice warm jacket",
    category: "Winter",
    image_url: "/placeholder.png",
  },
  {
    name: "Jeans",
    price: 2999,
    sizes: ["S", "M", "L", "XL"],
    description: "Classic blue juens",
    category: "Casual",
    image_url: "/placeholder.png",
  },
  {
    name: "Shirt",
    price: 2000,
    sizes: ["S", "M", "L"],
    description: "A fancy dress shirt",
    category: "Formal",
    image_url: "/placeholder.png",
  },
  {
    name: "Hoodie",
    price: 2000,
    sizes: ["M", "L"],
    description: "A comfortable hoodie",
    category: "Winter",
    image_url: "/placeholder.png",
  },
];
