import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "./ui/fonts";
import Navbar from "./ui/customer/navbar";
import { ThemeProvider } from "./ui/theme-provider";


export const metadata: Metadata = {
  title: "App Name",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          enableSystem
          defaultTheme="system"
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
